USE [master]
GO

/****** Object:  Database [ME]    Script Date: 20/02/2022 00:36:13 ******/
CREATE DATABASE [ME]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ME', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ME.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ME_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ME_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ME] SET ARITHABORT OFF 
GO

ALTER DATABASE [ME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ME] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ME] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ME] SET  MULTI_USER 
GO

ALTER DATABASE [ME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ME] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ME] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ME] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ME] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ME] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ME] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ME] SET  READ_WRITE 
GO

